##  Import the necessary libraries

In [4]:
import pandas as pd

## Import the dataset and assign it to a variable called gamo.

In [5]:
gamo = pd.read_csv('Video_Games_Sales_as_at_22_Dec_2016.csv')
gamo.head()

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
gamo.applymap(function, na_action= 'ignore')

NameError: name 'function' is not defined

## Select only the Name column.

In [6]:
gamo.Name

0                           Wii Sports
1                    Super Mario Bros.
2                       Mario Kart Wii
3                    Wii Sports Resort
4             Pokemon Red/Pokemon Blue
                     ...
16714    Samurai Warriors: Sanada Maru
16715                 LMA Manager 2007
16716          Haitaka no Psychedelica
16717                 Spirits & Spells
16718              Winning Post 8 2016
Name: Name, Length: 16719, dtype: object

## What is the number of columns in the dataset?

In [12]:
gamo.shape[1]

16

## Set the 'Name' column as the index of the dataframe

In [14]:
gamo.set_index('Name', inplace=True)

## View only the columns  Year_of_Release, Global_Sales and Rating and assign them to a dataframe called disciplineÂ¶

In [16]:
# filter only giving the column names

discipline = gamo[['Year_of_Release', 'Global_Sales', 'Rating']]
discipline

                               Year_of_Release  Global_Sales Rating
Name
Wii Sports                              2006.0         82.53      E
Super Mario Bros.                       1985.0         40.24    NaN
Mario Kart Wii                          2008.0         35.52      E
Wii Sports Resort                       2009.0         32.77      E
Pokemon Red/Pokemon Blue                1996.0         31.37    NaN
...                                        ...           ...    ...
Samurai Warriors: Sanada Maru           2016.0          0.01    NaN
LMA Manager 2007                        2006.0          0.01    NaN
Haitaka no Psychedelica                 2016.0          0.01    NaN
Spirits & Spells                        2003.0          0.01    NaN
Winning Post 8 2016                     2016.0          0.01    NaN

[16719 rows x 3 columns]

## Sort the games by Year_of_Release then to Global_Sales

In [21]:
discipline.sort_values(['Year_of_Release', 'Global_Sales'], ascending = False)

,Year_of_Release,Global_Sales,Rating
Name,,,
Imagine: Makeup Artist,2020.0,0.29,E
Phantasy Star Online 2 Episode 4: Deluxe Package,2017.0,0.04,NaN
Phantasy Star Online 2 Episode 4: Deluxe Package,2017.0,0.01,NaN
Brothers Conflict: Precious Baby,2017.0,0.01,NaN
FIFA 17,2016.0,7.59,E
...,...,...,...
PDC World Championship Darts 2008,NaN,0.01,E10+
Freaky Flyers,NaN,0.01,T
Inversion,NaN,0.01,M
Hakuouki: Shinsengumi Kitan,NaN,0.01,NaN
Virtua Quest,NaN,0.01,T

## Calculate the mean Global_Sales given per game

In [24]:
round(discipline['Global_Sales'].mean())

1

## Filter teams that made before 2010

In [31]:
gamo[gamo.Year_of_Release > 2010]

,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
Name,,,,,,,,,,,,,,,
Grand Theft Auto V,PS3,2013.0,Action,Take-Two Interactive,7.02,9.09,0.98,3.96,21.04,97.0,50.0,8.2,3994.0,Rockstar North,M
Grand Theft Auto V,X360,2013.0,Action,Take-Two Interactive,9.66,5.14,0.06,1.41,16.27,97.0,58.0,8.1,3711.0,Rockstar North,M
Call of Duty: Modern Warfare 3,X360,2011.0,Shooter,Activision,9.04,4.24,0.13,1.32,14.73,88.0,81.0,3.4,8713.0,"Infinity Ward, Sledgehammer Games",M
Call of Duty: Black Ops 3,PS4,2015.0,Shooter,Activision,6.03,5.86,0.36,2.38,14.63,NaN,NaN,NaN,NaN,NaN,NaN
Pokemon X/Pokemon Y,3DS,2013.0,Role-Playing,Nintendo,5.28,4.19,4.35,0.78,14.60,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Strawberry Nauts,PSV,2016.0,Adventure,Unknown,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
Aiyoku no Eustia,PSV,2014.0,Misc,dramatic create,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
Samurai Warriors: Sanada Maru,PS3,2016.0,Action,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
Haitaka no Psychedelica,PSV,2016.0,Adventure,Idea Factory,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
Winning Post 8 2016,PSV,2016.0,Simulation,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN

## Select the first 7 columns

In [46]:
# use .iloc to slices via the position of the passed integers
# : means all, 0:7 means from 0 to 7

gamo.iloc[: , 0:7]

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89
...,...,...,...,...,...,...,...
16714,Samurai Warriors: Sanada Maru,PS3,2016.0,Action,Tecmo Koei,0.00,0.00
16715,LMA Manager 2007,X360,2006.0,Sports,Codemasters,0.00,0.01
16716,Haitaka no Psychedelica,PSV,2016.0,Adventure,Idea Factory,0.00,0.00
16717,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00
16718,Winning Post 8 2016,PSV,2016.0,Simulation,Tecmo Koei,0.00,0.00

## Select all columns except the last 3.

In [48]:
gamo.iloc[: , :-3]

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16714,Samurai Warriors: Sanada Maru,PS3,2016.0,Action,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN
16715,LMA Manager 2007,X360,2006.0,Sports,Codemasters,0.00,0.01,0.00,0.00,0.01,NaN,NaN,NaN
16716,Haitaka no Psychedelica,PSV,2016.0,Adventure,Idea Factory,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN
16717,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,NaN,NaN,NaN
16718,Winning Post 8 2016,PSV,2016.0,Simulation,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN

##  Present only the Genre for Pokemon X/Pokemon Y, Aiyoku no Eustia and Winning Post 8 2016.

In [51]:
# .loc is another way to slice, using the labels of the columns and indexes
gamo.loc[gamo.Name.isin( ['Pokemon X/Pokemon Y', 'Aiyoku no Eustia', 'Winning Post 8 2016']), ['Name', 'Genre']]

                      Name         Genre
33     Pokemon X/Pokemon Y  Role-Playing
15601  Winning Post 8 2016    Simulation
16711     Aiyoku no Eustia          Misc
16718  Winning Post 8 2016    Simulation